# -*- coding: utf-8 -*-
"""irisClassification2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195wNR36XIx2oC9Rd4tsVmVTx-6vJWnRc
"""

import numpy as np
import pandas as pd

df = pd.DataFrame(pd.read_csv('Iris.csv'))

df.groupby('Species').size()

X = df.iloc[:, 1:5]
y = pd.DataFrame(df.iloc[:, 5])

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y['Species'] = le.fit_transform(y['Species'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

from sklearn.linear_model import LogisticRegression
Lr = LogisticRegression()
Lr.fit(X_train,y_train)

y_pred = Lr.predict(X_test)

print(le.inverse_transform(y_pred))